#!/bin/sh
# Display currently playing music metadata.

case "$BLOCK_BUTTON" in
    1) mpc prev ;;
    2) mpc toggle ;;
    3) mpc next ;;
    4) mpc seek +5 ;;
    5) mpc seek -5 ;;
    6) terminal -e "$EDITOR" "$0" ;;
esac

set -- --player spotify,mpv,%any
icon=""
pausedIcon=""
if status="$(playerctl "$@" status 2>&1)" && [ "$status" != "Stopped" ]; then
    [ "$status" = "Paused" ] && icon="$pausedIcon"
    currentSong="$(playerctl "$@" metadata --format "{{title}} - {{artist}}")"
else
    [ "$(mpc status "%state%")" = "paused" ] && icon="$pausedIcon"
    currentSong="$(mpc current -f "%title%" | sed 's/\(.\{22\}\).*/\1.../')"
fi

[ -z "$currentSong" ] && exit

. sb-theme
display "$icon $currentSong"
