#!/bin/sh
# This simple script uses dmenu to ask the user what they wanna do.

USER_OPT1=$(printf "[]= (Flextile) Tiled\n><> (Flextile) Floating\n[M] (Flextile) Monocle\n||| (Flextile) Columns\n>M> (Flextile) Floating Master\n[D] (Flextile) Deck\nTTT (Flextile) Bottom Stack\n=== (Flextile) Bottom Stack Horizontal\n|M| (Flextile) Centered Naster\n-M- (Flextile) Centered Master Horizontal\n::: (Flextile) Gapless Grid\n[\\] (Flextile) Fibonacci Dwindle\n(@) (Flextile) Fibonacci Spiral\n[T] (Flextile) Tatami Tats\n[]= Tiled\n[M] Monocle\nTTT Bottom Stack\n=== Bottom Stack Horizontal\n|M| Centered Master\n>M> Centered Floating Master\n||| Columns\n[D] Deck\n(@) Fibonacci Spiral\n[\\] Fibonacci Dwindle\nHHH Grid\n--- Horizontal Grid\n::: Gapless Grid\n### N-row Grid" | spmenu -l 10 -g 1 -p "[?] Layout?")


case "$USER_OPT1" in
"[]= (Flextile) Tiled") dwm-msg run_command setlayoutsafe 4313472 ;;
"><> (Flextile) Floating") dwm-msg run_command setlayoutsafe 4313520 ;;
"[M] (Flextile) Monocle") dwm-msg run_command setlayoutsafe 4313568 ;;
"||| (Flextile) Columns") dwm-msg run_command setlayoutsafe 4313616 ;;
">M> (Flextile) Floating Master") dwm-msg run_command setlayoutsafe 4313664 ;;
"[D] (Flextile) Deck") dwm-msg run_command setlayoutsafe 4313712 ;;
"TTT (Flextile) Bottom Stack") dwm-msg run_command setlayoutsafe 4313760 ;;
"=== (Flextile) Bottom Stack Horizontal") dwm-msg run_command setlayoutsafe 4313808 ;;
"|M| (Flextile) Centered Naster") dwm-msg run_command setlayoutsafe 4313856 ;;
"-M- (Flextile) Centered Master Horizontal") dwm-msg run_command setlayoutsafe 4313904 ;;
"::: (Flextile) Gapless Grid") dwm-msg run_command setlayoutsafe 4313952 ;;
"[\] (Flextile) Fibonacci Dwindle") dwm-msg run_command setlayoutsafe 4314000 ;;
"(@) (Flextile) Fibonacci Spiral") dwm-msg run_command setlayoutsafe 4314048 ;;
"[T] (Flextile) Tatami Tats") dwm-msg run_command setlayoutsafe 4314096 ;;
"[]= Tiled") dwm-msg run_command setlayoutsafe 4314144 ;;
"[M] Monocle") dwm-msg run_command setlayoutsafe 4314192 ;;
"TTT Bottom Stack") dwm-msg run_command setlayoutsafe 4314240 ;;
"=== Bottom Stack Horizontal") dwm-msg run_command setlayoutsafe 4314288 ;;
"|M| Centered Master") dwm-msg run_command setlayoutsafe 4314336 ;;
">M> Centered Floating Master") dwm-msg run_command setlayoutsafe 4314384 ;;
"||| Columns") dwm-msg run_command setlayoutsafe 4314432 ;;
"[D] Deck") dwm-msg run_command setlayoutsafe 4314480 ;;
"(@) Fibonacci Spiral") dwm-msg run_command setlayoutsafe 4314528 ;;
"[\] Fibonacci Dwindle") dwm-msg run_command setlayoutsafe 4314576 ;;
"HHH Grid") dwm-msg run_command setlayoutsafe 4314624 ;;
"--- Horizontal Grid") dwm-msg run_command setlayoutsafe 4314672 ;;
"::: Gapless Grid") dwm-msg run_command setlayoutsafe 4314720 ;;
"### N-row Grid") dwm-msg run_command setlayoutsafe 4314768 ;;
"") exit 0 ;;
esac
