name: Build

on:
  push:
    branches: [ master ]

# NOTE: "stable" tcc is too old and fails at linking. instead fetching a recent known working commit.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dep
      run: |
        sudo apt-get update
        sudo apt-get install libimlib2 libimlib2-dev xserver-xorg-core xserver-xorg-dev \
                             libxft2 libxft-dev libexif12 libexif-dev \
                             gcc clang git bc
        TCC_SHA="29ae3ed4d5b83eec43598d6cd7949bccb41c8083"
        wget "https://github.com/TinyCC/tinycc/archive/${TCC_SHA}.tar.gz" && tar xzf "${TCC_SHA}.tar.gz"
        ( cd "tinycc-$TCC_SHA" && ./configure && make -j"$(nproc)" && sudo make install; )
    - name: build
      run: |
        CFLAGS="$(sed '/^#/d' etc/woodpecker/CFLAGS | paste -d ' ' -s)"
        build () {
          for cc in "gcc" "clang"; do
            echo "### $cc - $2 build ###"
            make clean && make -s -j"$(nproc)" CC="$cc" CFLAGS="$CFLAGS" LDFLAGS="$CFLAGS" OPT_DEP_DEFAULT="$1"
          done
        }
        # try all combination with tcc #
        etc/woodpecker/try-all-builds.sh
        # full-build with gcc and clang #
        build "1" "full"
        # ensure minimal-build works without opt deps installed
        sudo apt-get remove libxft2 libxft-dev libexif12 libexif-dev >/dev/null
        build "0" "minimal"
  macOS-build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: dep
        run: |
          brew update
          # see: https://github.com/actions/setup-python/issues/577
          brew install imlib2 libx11 libxft libexif || true
      - name: build
        run: |
          # libinotify-kqueue isn't available on homebrew
          make clean && make -s OPT_DEP_DEFAULT=1 HAVE_INOTIFY=0
          # force uninstallation with --ignore-dependencies
          brew uninstall --ignore-dependencies libxft libexif
          make clean && make -s OPT_DEP_DEFAULT=0
