static int width_stbutton(Bar *bar, BarArg *a);
static int draw_stbutton(Bar *bar, BarArg *a);
static int click_stbutton(Bar *bar, Arg *arg, BarArg *a);
static int width_stbutton2(Bar *bar, BarArg *a);
static int draw_stbutton2(Bar *bar, BarArg *a);
static int click_stbutton2(Bar *bar, Arg *arg, BarArg *a);
static int width_stbutton3(Bar *bar, BarArg *a);
static int draw_stbutton3(Bar *bar, BarArg *a);
static int click_stbutton3(Bar *bar, Arg *arg, BarArg *a);
static int width_stbutton4(Bar *bar, BarArg *a);
static int draw_stbutton4(Bar *bar, BarArg *a);
static int click_stbutton4(Bar *bar, Arg *arg, BarArg *a);
static int width_stbutton5(Bar *bar, BarArg *a);
static int draw_stbutton5(Bar *bar, BarArg *a);
static int click_stbutton5(Bar *bar, Arg *arg, BarArg *a);
