#!/bin/sh
systemctl --user restart clipmenud.service # restarts clipmenud, if installed
wal -R # could be changed
picom -b # launches compositor
/usr/local/bin/dwmblocks & # launches slstatus/dwmblocks
/usr/bin/dunst & # launches dunst daemon
nm-applet & # optional, launch network-manager applet
/usr/local/bin/eww daemon & # launch eww in start up, assumes eww is copied to $PATH
/usr/local/bin/eww open main & # make sure the config is copied
nemo-desktop & # launch nemo in desktop mode, to provide desktop icons, optional
exec /usr/local/bin/dwm # launch dwm
