#!/bin/sh
systemctl --user restart clipmenud.service # restarts clipmenud, if installed
wal -R # could be changed
picom -b # launches compositor
/usr/local/bin/dwmblocks & # launches slstatus/dwmblocks
/usr/bin/dunst & # launches dunst daemon
paplay /usr/share/sounds/Oxygen-Sys-Special.ogg # autoplay sound, optional
nm-applet & # optional, launch network-manager applet
nemo-desktop & # launch nemo in desktop mode, to provide desktop icons, optional
exec /usr/local/bin/dwm # launch dwm
